name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Pull latest changes
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "thehmanshusingh@gmail.com"
          git config --global user.name "TheRanomial"
          git pull https://himanshusngh2026:$HF_TOKEN@huggingface.co/spaces/himanshusngh2026/Summarize_content main --rebase

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://himanshusngh2026:$HF_TOKEN@huggingface.co/spaces/himanshusngh2026/Summarize_content main
